### ISSUE TITLE
Search image on Google does not work

### ISSUE THREAD

**Issue by jkalmar** [jle64/nautilus-search-by-image#1]
Hi,  
  
Just tried this extension and the google option does not work. The Yandex works fine.  
  
I'm using Gnome 42.5 on Ubuntu 22.04.  
  
If you need logs or more details or some testing please let me know what you need and I will provide it.  
  
Thanks

**Comment by jle64** [comment]
Hey, thanks for reporting this. It looks like Google changed their URL format and I don't know how to use the new one, so for now at least I'm removing the Google option.

BTW I updated the script for a more recent version of the Nautilus API as otherwise I couldn't run it on my machine, so this version probably requires a newer version of Nautilus.
